server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SaltedFish-Extreme/tensquare.git
  rabbitmq:
    host: 192.168.68.129
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh