server:
  port: 9005
spring:
  application:
    name: tensquare-gathering #指定服务名
  datasource:
    url: jdbc:mysql://192.168.68.129:3306/tensquare_gathering?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true